[2024-12-26 16:27:46,980] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2024-12-26T16:26:00.327720+00:00 [None]>
[2024-12-26 16:27:46,992] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2024-12-26T16:26:00.327720+00:00 [None]>
[2024-12-26 16:27:46,992] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:27:46,993] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-26 16:27:46,993] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:27:47,004] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2024-12-26T16:26:00.327720+00:00
[2024-12-26 16:27:47,007] {standard_task_runner.py:52} INFO - Started process 272 to run task
[2024-12-26 16:27:47,010] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_one', '2024-12-26T16:26:00.327720+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpc23pqdd0', '--error-file', '/tmp/tmpmih4tyyb']
[2024-12-26 16:27:47,011] {standard_task_runner.py:77} INFO - Job 21: Subtask task_one
[2024-12-26 16:27:47,043] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_one 2024-12-26T16:26:00.327720+00:00 [running]> on host d88713c29571
[2024-12-26 16:27:47,082] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T16:26:00.327720+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T16:26:00.327720+00:00
[2024-12-26 16:27:47,162] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m1a.html
[2024-12-26 16:27:47,162] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:28:02,175] {logging_mixin.py:104} INFO - m1a.html
[2024-12-26 16:28:02,176] {logging_mixin.py:104} INFO - Wrote file: m1a.html
[2024-12-26 16:28:02,238] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m1b.html
[2024-12-26 16:28:02,238] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:28:17,244] {logging_mixin.py:104} INFO - m1b.html
[2024-12-26 16:28:17,245] {logging_mixin.py:104} INFO - Wrote file: m1b.html
[2024-12-26 16:28:17,319] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m1c.html
[2024-12-26 16:28:17,320] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:28:32,335] {logging_mixin.py:104} INFO - m1c.html
[2024-12-26 16:28:32,337] {logging_mixin.py:104} INFO - Wrote file: m1c.html
[2024-12-26 16:28:32,417] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m2a.html
[2024-12-26 16:28:32,417] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:28:47,431] {logging_mixin.py:104} INFO - m2a.html
[2024-12-26 16:28:47,433] {logging_mixin.py:104} INFO - Wrote file: m2a.html
[2024-12-26 16:28:47,516] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m2b.html
[2024-12-26 16:28:47,516] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:29:02,532] {logging_mixin.py:104} INFO - m2b.html
[2024-12-26 16:29:02,534] {logging_mixin.py:104} INFO - Wrote file: m2b.html
[2024-12-26 16:29:02,614] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m2c.html
[2024-12-26 16:29:02,614] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:29:17,621] {logging_mixin.py:104} INFO - m2c.html
[2024-12-26 16:29:17,621] {logging_mixin.py:104} INFO - Wrote file: m2c.html
[2024-12-26 16:29:17,694] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m3a.html
[2024-12-26 16:29:17,695] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:29:32,710] {logging_mixin.py:104} INFO - m3a.html
[2024-12-26 16:29:32,711] {logging_mixin.py:104} INFO - Wrote file: m3a.html
[2024-12-26 16:29:32,804] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m3b.html
[2024-12-26 16:29:32,805] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:29:47,819] {logging_mixin.py:104} INFO - m3b.html
[2024-12-26 16:29:47,820] {logging_mixin.py:104} INFO - Wrote file: m3b.html
[2024-12-26 16:29:47,887] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m4a.html
[2024-12-26 16:29:47,888] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:30:02,904] {logging_mixin.py:104} INFO - m4a.html
[2024-12-26 16:30:02,904] {logging_mixin.py:104} INFO - Wrote file: m4a.html
[2024-12-26 16:30:02,974] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m4b.html
[2024-12-26 16:30:02,974] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:30:17,987] {logging_mixin.py:104} INFO - m4b.html
[2024-12-26 16:30:17,988] {logging_mixin.py:104} INFO - Wrote file: m4b.html
[2024-12-26 16:30:18,054] {logging_mixin.py:104} INFO - pulled: http://student.mit.edu/catalog/m4c.html
[2024-12-26 16:30:18,055] {logging_mixin.py:104} INFO - --- waiting ---
[2024-12-26 16:30:33,019] {local_task_job.py:199} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-26 16:30:33,021] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 272
[2024-12-26 16:30:33,022] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-26 16:30:33,029] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1356, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 102, in catalog
    time.sleep(15)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-26 16:30:33,040] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=assignment, task_id=task_one, execution_date=20241226T162600, start_date=20241226T162746, end_date=20241226T163033
[2024-12-26 16:30:33,075] {process_utils.py:66} INFO - Process psutil.Process(pid=272, status='terminated', exitcode=1, started='16:27:46') (272) terminated with exit code 1
