[2024-12-26 18:41:33,384] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_two 2024-12-26T18:40:17.282029+00:00 [None]>
[2024-12-26 18:41:33,399] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_two 2024-12-26T18:40:17.282029+00:00 [None]>
[2024-12-26 18:41:33,400] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 18:41:33,401] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2024-12-26 18:41:33,401] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 18:41:33,410] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_two> on 2024-12-26T18:40:17.282029+00:00
[2024-12-26 18:41:33,416] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_two', '2024-12-26T18:40:17.282029+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpgyyzr8ri', '--error-file', '/tmp/tmpp2zjjzj8']
[2024-12-26 18:41:33,414] {standard_task_runner.py:52} INFO - Started process 1043 to run task
[2024-12-26 18:41:33,417] {standard_task_runner.py:77} INFO - Job 32: Subtask task_two
[2024-12-26 18:41:33,455] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_two 2024-12-26T18:40:17.282029+00:00 [running]> on host d88713c29571
[2024-12-26 18:41:33,498] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_two
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T18:40:17.282029+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T18:40:17.282029+00:00
[2024-12-26 18:41:33,506] {python.py:151} INFO - Done. Returned value was: None
[2024-12-26 18:41:33,518] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_two, execution_date=20241226T184017, start_date=20241226T184133, end_date=20241226T184133
[2024-12-26 18:41:33,549] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-26 18:41:33,591] {local_task_job.py:151} INFO - Task exited with return code 0
