[2024-12-26 16:06:47,480] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:06:32.796524+00:00 [None]>
[2024-12-26 16:06:47,493] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:06:32.796524+00:00 [None]>
[2024-12-26 16:06:47,493] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:06:47,494] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-26 16:06:47,494] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:06:47,503] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-26T16:06:32.796524+00:00
[2024-12-26 16:06:47,506] {standard_task_runner.py:52} INFO - Started process 195 to run task
[2024-12-26 16:06:47,510] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-26T16:06:32.796524+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpsfv7o0fi', '--error-file', '/tmp/tmp44dn1csr']
[2024-12-26 16:06:47,511] {standard_task_runner.py:77} INFO - Job 14: Subtask task_zero
[2024-12-26 16:06:47,543] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-26T16:06:32.796524+00:00 [running]> on host d88713c29571
[2024-12-26 16:06:47,585] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T16:06:32.796524+00:00
[2024-12-26 16:06:47,586] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-26 16:06:47,586] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-26 16:06:47,593] {subprocess.py:75} INFO - Output:
[2024-12-26 16:06:48,433] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-26 16:06:48,613] {subprocess.py:79} INFO - Collecting beautifulsoup4
[2024-12-26 16:06:48,669] {subprocess.py:79} INFO -   Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
[2024-12-26 16:06:48,761] {subprocess.py:79} INFO - Collecting soupsieve>1.2
[2024-12-26 16:06:48,773] {subprocess.py:79} INFO -   Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
[2024-12-26 16:06:51,524] {subprocess.py:79} INFO - Installing collected packages: soupsieve, beautifulsoup4
[2024-12-26 16:06:51,644] {subprocess.py:79} INFO - Successfully installed beautifulsoup4-4.12.3 soupsieve-2.3.2.post1
[2024-12-26 16:06:51,864] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-26 16:06:51,894] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241226T160632, start_date=20241226T160647, end_date=20241226T160651
[2024-12-26 16:06:51,944] {local_task_job.py:151} INFO - Task exited with return code 1
