[2024-12-26 18:46:38,605] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T18:46:02.161925+00:00 [None]>
[2024-12-26 18:46:38,619] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T18:46:02.161925+00:00 [None]>
[2024-12-26 18:46:38,620] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 18:46:38,621] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-26 18:46:38,622] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 18:46:38,628] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-26T18:46:02.161925+00:00
[2024-12-26 18:46:38,632] {standard_task_runner.py:52} INFO - Started process 1498 to run task
[2024-12-26 18:46:38,635] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-26T18:46:02.161925+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpi87ckehq', '--error-file', '/tmp/tmplbk45445']
[2024-12-26 18:46:38,636] {standard_task_runner.py:77} INFO - Job 36: Subtask task_zero
[2024-12-26 18:46:38,668] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-26T18:46:02.161925+00:00 [running]> on host d88713c29571
[2024-12-26 18:46:38,706] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T18:46:02.161925+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T18:46:02.161925+00:00
[2024-12-26 18:46:38,707] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-26 18:46:38,708] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-26 18:46:38,715] {subprocess.py:75} INFO - Output:
[2024-12-26 18:46:39,287] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-26 18:46:39,339] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-12-26 18:46:39,343] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-12-26 18:46:41,893] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-26 18:46:41,921] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241226T184602, start_date=20241226T184638, end_date=20241226T184641
[2024-12-26 18:46:41,943] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-26 18:46:41,987] {local_task_job.py:151} INFO - Task exited with return code 0
