[2024-12-26 16:17:34,198] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:16:06.432677+00:00 [None]>
[2024-12-26 16:17:34,212] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:16:06.432677+00:00 [None]>
[2024-12-26 16:17:34,213] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:17:34,214] {taskinstance.py:1088} INFO - Starting attempt 2 of 4
[2024-12-26 16:17:34,215] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:17:34,222] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-26T16:16:06.432677+00:00
[2024-12-26 16:17:34,226] {standard_task_runner.py:52} INFO - Started process 1171 to run task
[2024-12-26 16:17:34,228] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-26T16:16:06.432677+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp4ho5avap', '--error-file', '/tmp/tmpmf77b6kp']
[2024-12-26 16:17:34,230] {standard_task_runner.py:77} INFO - Job 17: Subtask task_zero
[2024-12-26 16:17:34,263] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-26T16:16:06.432677+00:00 [running]> on host d88713c29571
[2024-12-26 16:17:34,305] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T16:16:06.432677+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T16:16:06.432677+00:00
[2024-12-26 16:17:34,307] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-26 16:17:34,307] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-26 16:17:34,313] {subprocess.py:75} INFO - Output:
[2024-12-26 16:17:34,890] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-26 16:17:34,940] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-12-26 16:17:34,945] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-12-26 16:17:37,691] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-26 16:17:37,717] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241226T161606, start_date=20241226T161734, end_date=20241226T161737
[2024-12-26 16:17:37,739] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-26 16:17:37,780] {local_task_job.py:151} INFO - Task exited with return code 0
